baseURL = "https://jeffrytandiono.com"
title = "Jeffry Tandiono"
theme = "dream-plus"
paginate = 4
enableRobotsTXT = true
disqusShortname = "dream-plus"

#Skip building these files
ignoreFiles = ["content/404.md", "content/about.md", "content/cards/\\.*"]

#Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	#Favicon for site
	favicon = "/favicon/favicon.ico"

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	siteStartYear = 2019

	[params.author]
		name = "Jeffry Tandiono"
		description = "Just a boy posting random stuff, mostly tech-related."
		avatar = "/images/avatar.jpg"
		motto = "A keen maker, programmer and an instructables author."

	[params.features]
		#Enable Twitter Emoji
		twitterEmoji = true
		#Enable Table of Contents
		toc = true
		#Enable share card
		shareCard = true
		#Use custom CSS
		customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	#Tags settings
	[params.tags]
		enabled = true

	#Categories settings
	[params.categories]
		enabled = true

[social]
	email = "jeffry.tandiono@gmail.com"
	github = "Chensienyong"
	stackoverflow = "chensienyong"
	medium = "chensienyong"
